name: magicli
description: A sample command-line application with basic argument parsing.
version: 0.0.3
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  ansicolor: ^2.0.2
  args: ^2.4.2
  flutter_bloc: ^8.1.5
  path: ^1.9.0
  sprintf: ^7.0.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
